POST http://localhost:8080/api/waiting-list/bobulova/entries 

{"id":"@new","name":"r","patientId":"az","waitingSince":"2025-04-15T14:48:57.873Z","estimatedStart":"2025-04-15T14:48:57.937Z","estimatedDurationMinutes":15}